// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Node struct {
	ID               string       `json:"id"`
	IpAddress        string       `json:"ip_address"`
	ServerPublicKey  string       `json:"server_public_key"`
	Port             int64        `json:"port"`
	Status           string       `json:"status"`
	Version          int64        `json:"version"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	DestroyAt        sql.NullTime `json:"destroy_at"`
	LastHandshakeAt  sql.NullTime `json:"last_handshake_at"`
	ConnectedClients int64        `json:"connected_clients"`
}
