// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ----------------------------------------------------------------------------
	// Atomic Operations (Use with transactions)
	// ----------------------------------------------------------------------------
	// Mark old node for destruction during rotation
	// USE IN TRANSACTION with CreateNode
	BeginRotation(ctx context.Context, arg BeginRotationParams) error
	// Cancel scheduled destruction (FR-13)
	CancelNodeDestruction(ctx context.Context, arg CancelNodeDestructionParams) error
	// ============================================================================
	// MIGRATION HELPERS
	// ============================================================================
	// DANGEROUS: Delete all nodes (for testing/reset only)
	CleanupAllNodes(ctx context.Context) error
	// ----------------------------------------------------------------------------
	// Node Creation & Updates
	// ----------------------------------------------------------------------------
	// Create a new node (FR-3, FR-9)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	// Permanently delete a node (FR-8, FR-25)
	DeleteNode(ctx context.Context, id string) error
	// Get the currently active node (FR-17)
	// Returns the most recently created active node to handle transition edge cases
	GetActiveNode(ctx context.Context) (Node, error)
	// Get all nodes (for debugging/admin)
	GetAllNodes(ctx context.Context) ([]Node, error)
	// Get schema version for migrations
	GetDatabaseVersion(ctx context.Context) (string, error)
	// Get nodes with no activity for idle timeout period (FR-12)
	// Considers a node idle if:
	// 1. No clients connected, OR
	// 2. Last handshake was more than idle_minutes ago
	GetIdleNodes(ctx context.Context, dollar_1 sql.NullString) ([]Node, error)
	// Get the most recently created node regardless of status
	GetLatestNode(ctx context.Context) (Node, error)
	// ----------------------------------------------------------------------------
	// Node Retrieval
	// ----------------------------------------------------------------------------
	// Get a specific node by ID
	GetNode(ctx context.Context, id string) (Node, error)
	// ----------------------------------------------------------------------------
	// Health & Statistics
	// ----------------------------------------------------------------------------
	// Count nodes by status
	GetNodeCount(ctx context.Context) (GetNodeCountRow, error)
	// Get node with lock for update (use in transaction)
	// SQLite doesn't have SELECT FOR UPDATE, but this documents intent
	GetNodeForUpdate(ctx context.Context, id string) (Node, error)
	// Get all nodes with a specific status
	GetNodesByStatus(ctx context.Context, status string) ([]Node, error)
	// ----------------------------------------------------------------------------
	// Rotation & Cleanup Queries
	// ----------------------------------------------------------------------------
	// Get nodes that need rotation (FR-2)
	// Active nodes older than rotation interval
	GetNodesDueForRotation(ctx context.Context, dollar_1 sql.NullString) ([]Node, error)
	// Get nodes whose grace period has expired (FR-8)
	GetNodesForDestruction(ctx context.Context) ([]Node, error)
	// Get all nodes with scheduled destruction (for monitoring)
	GetNodesScheduledForDestruction(ctx context.Context) ([]Node, error)
	// Get nodes stuck in non-terminal states (FR-25)
	// Provisioning for >1 hour or destroying for >1 hour
	GetOrphanedNodes(ctx context.Context) ([]Node, error)
	// Sum of all connected clients across all nodes
	GetTotalConnectedClients(ctx context.Context) (interface{}, error)
	// Quick check if any active node exists (FR-17, FR-20)
	HasActiveNode(ctx context.Context) (int64, error)
	// Transition node from provisioning to active (FR-6)
	MarkNodeActive(ctx context.Context, arg MarkNodeActiveParams) error
	// Mark node for destruction with grace period (FR-7, FR-8)
	ScheduleNodeDestruction(ctx context.Context, arg ScheduleNodeDestructionParams) error
	// Update last handshake time and client count (FR-10, FR-11)
	UpdateNodeActivity(ctx context.Context, arg UpdateNodeActivityParams) error
	// Update node status with optimistic locking (FR-16)
	// Returns error if version doesn't match (concurrent modification)
	UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error
}

var _ Querier = (*Queries)(nil)
