FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN cd cmd/connector && go build -o /vpn-rotator

FROM alpine:latest
RUN apk --no-cache add ca-certificates wireguard-tools
COPY --from=builder /vpn-rotator /usr/local/bin/vpn-rotator

ENTRYPOINT ["/usr/local/bin/vpn-rotator"]
